name: Microfrontend with Single-SPA + VueJS
rating: 5
imageUrl: https://github.com/msa-ez/topping-spring-security/assets/123912988/0a910647-98f8-4e7d-b0c8-7a40e223dead
description: Microfrontend VueJS template with Sing-SPA
tags:
  - frontend
  - microfrontend
  - single-spa
