name: Microfrontend with Single-SPA + VueJS
rating: 5
imageUrl: https://github.com/kibum0405/topping-wijmo/assets/59447401/3cf4bb64-9128-4eae-8aba-7e70cb8b55fb
description: Microfrontend VueJS template with Sing-SPA
tags:
  - frontend
  - microfrontend
  - single-spa
