---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-root
  labels:
    app: frontend-root
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-root
  template:
    metadata:
      labels:
        app: frontend-root
    spec:
      containers:
        - name: frontend
          image: username/frontend:latest
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 9000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 9000
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5